### ISSUE TITLE
How does this perform?

### ISSUE THREAD

**Issue by infogulch** [samber/slog-parquet#4]
Hi!

I found this package because I suspected that dumping slog logs into a parquet file would be relatively efficient in terms of cpu overhead and bandwidth when compressed, especially compared to streaming json, and something like this package is what I'd hope I could make if I made it myself.

Have you had much experience with the performance of this package? How efficient is it compared to other logger handlers?

Thanks!
Joe

**Comment by samber** [comment]
I suppose pushing to kafka would be more efficient for the memory, than buffering. Also a 30min parquet buffer might lead to data loss in case of server failure.

**Comment by infogulch** [comment]
If a few dozen MB of memory is a problem then you're running in a very constrained environment. If traffic is too infrequent to fill the buffer in a reasonable amount of time, maybe a timer that triggers an early upload if some minimum `time.Duration` threshold is passed would be a good addition.

These are reasonable downsides to consider when using the `slog-parquet` package, but I am also interested in scenarios where this package could provide benefits. I suspect high traffic, CPU limited scenarios would be a good case for this.

Compared to a JSON logger, how much CPU does it take? How much bandwidth does it use? Have you tried compressing the parquet files?
